/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './*.{js,ts,jsx,tsx}', './components/*.{js,ts,jsx,tsx}', './utils/*.{js,ts,jsx,tsx}'],
  important: '#root',
  safelist: [
    // Spacing utilities
    'mt-4',
    'mt-8',
    'mb-4',
    'mb-2',
    'mb-1',
    'py-3',
    'px-4',
    'py-1',
    'px-3',
    // Text utilities
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'font-bold',
    'font-normal',
    // Display utilities
    'inline-block',
    'block',
    'flex',
    'grid',
    'hidden',
    // Border radius
    'rounded-lg',
    'rounded-full',
    'rounded-md',
    // Colors (inline values)
    'bg-[#00D373]',
    'bg-[#00D373]/80',
    'bg-[#00D373]/20',
    'bg-[#F4BC42]',
    'bg-[#F4BC42]/20',
    'text-[#111111]',
    'text-white',
    // Layout utilities
    'w-full',
    'w-40',
    'w-24',
    'w-16',
    'h-3',
    'w-3',
    // Position utilities
    'absolute',
    'relative',
    'sticky',
    'top-8',
    // Flexbox utilities
    'flex-col',
    'items-center',
    'items-start',
    'justify-between',
    'justify-center',
    'gap-4',
    'gap-6',
    'gap-3',
    'space-y-4',
    // Grid utilities
    'grid-cols-1',
    'md:grid-cols-2',
    // Responsive utilities
    'md:p-8',
    'md:grid-cols-2',
    // Other utilities
    'min-h-screen',
    'max-w-4xl',
    'mx-auto',
    'p-4',
    'p-6',
    'p-3',
    'border-b',
    'border-gray-100',
    'border-gray-300',
    'last:border-b-0',
    'shadow-sm',
    'shadow-[0_2px_8px_rgba(0,0,0,0.1)]',
    'transition-colors',
    'transition-transform',
    'active:scale-95',
    'focus:border-[#00D373]',
    'focus:ring',
    'focus:ring-[#00D373]',
    'focus:ring-opacity-50',
    'accent-[#00D373]',
    'hover:bg-opacity-90',
    'transform',
    'translate-y-1/2',
    '-translate-y-1/2',
    'left-3',
    'right-3',
    'top-1/2',
    'pl-7',
    'pr-3',
    'pl-3',
    'pr-7',
    'text-center',
    'text-left',
    'text-right',
    'opacity-90',
    'opacity-1',
    // Breakdown colors
    'bg-[#CC0000]',
    'bg-[#183D33]',
    'bg-[#FF8133]',
    // Custom alignment utilities
    'text-left-important',
    'text-center-important',
    'text-right-important',
    // Custom width utilities
    'w-full-important',
  ],
  theme: {
    extend: {
      colors: {
        // Preserve all custom colors from the current app
        'primary-green': '#00D373',
        'warning-yellow': '#F4BC42',
        'background-gray': '#F8F9FA',
        'text-dark': '#111111',
        // Breakdown colors from constants.ts
        obligation: '#CC0000',
        earning: '#00D373',
        figure: '#183D33',
        opEx: '#FF8133',
      },
      fontFamily: {
        sans: ['Source Sans Pro', 'sans-serif'],
      },
      boxShadow: {
        card: '0 2px 8px rgba(0,0,0,0.1)',
      },
    },
  },
  plugins: [],
};
